### ISSUE TITLE
Loading gif has neutral bg on initial load on #login against white background

### ISSUE THREAD

**Issue by maxennnnn** [mustafamusse/Home-Bar#44]

**Comment by mustafamusse** [comment]
this is because i pushed up a new logo with bg-neutral as background, if we want a white one, we need to add a new spinner.gif with white background instead.

**Comment by mustafamusse** [comment]
What we can do is use a transparent gif instead

**Comment by maxennnnn** [comment]
Or maybe have bg-neutral on initial load before we show the spinner icon? Or remove it on start screen

**Comment by maxennnnn** [comment]
> What we can do is use a transparent gif instead

Yeah that works as well!
